"""Run a manual-lab export and measurement-ingestion smoke check."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export one validated manual laboratory plan, ingest a completed "
            "measurement file, and save the resulting BO observation ledger."
        )
    )
    parser.add_argument("--scenario", default="inherent_selectivity")
    parser.add_argument("--run-id", default="manual_lab_smoke")
    parser.add_argument("--candidate-id", default="manual_cand_smoke_001")
    parser.add_argument("--seed", type=int, default=1010)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results") / "bo10_manual_lab_smoke",
    )
    return parser.parse_args()


def main() -> None:
    from asd_agent.bo.manual_lab import (
        ManualCandidate,
        ManualLabBackend,
        ManualMeasurementRecord,
        write_measurement_csv,
        write_measurement_json,
    )
    from asd_agent.bo.stage2 import Stage2Decision, simulate_stage2
    from asd_agent.config import load_stage2_scenario

    args = parse_args()
    config = load_stage2_scenario(args.scenario)
    decision = Stage2Decision(
        precursor_dose_s=config.hard_bounds.precursor_dose_s.midpoint(),
        temperature_c=config.hard_bounds.temperature_c.midpoint(),
        cycle_count=int(config.hard_bounds.cycle_count.max),
    )
    backend = ManualLabBackend(config, run_id=args.run_id)
    plan = backend.receive_candidate(
        ManualCandidate(
            candidate_id=args.candidate_id,
            decision=decision,
            optimizer="manual_lab_smoke",
        ),
        experiment_id="manual_001",
        operator_notes="Smoke-exported plan for tutorial verification.",
    )
    plan_csv, plan_json = backend.export_plan(args.output_dir)
    template_csv = backend.export_measurement_template(args.output_dir)

    outcomes = simulate_stage2(config, decision, seed=args.seed)
    measurement = ManualMeasurementRecord(
        experiment_id=plan.experiment_id,
        ga_thickness=outcomes.ga_thickness_nm,
        nga_thickness=outcomes.nga_thickness_nm,
        units="nm",
        ga_uncertainty=config.process.noise_sigma_nm,
        nga_uncertainty=config.process.noise_sigma_nm,
        measurement_method="virtual smoke measurement",
        replicate_identifier="replicate_001",
        quality_control_status="pass",
        operator_notes="Generated by smoke script; not a laboratory result.",
    )
    measurement_csv = args.output_dir / "manual_lab_measurements.csv"
    measurement_json = args.output_dir / "manual_lab_measurements.json"
    write_measurement_csv([measurement], measurement_csv)
    write_measurement_json([measurement], measurement_json)

    observations = backend.import_completed_measurements(measurement_csv)
    ledger_json = args.output_dir / "manual_lab_ledger.json"
    ledger_json.write_text(
        json.dumps([observation.model_dump(mode="json") for observation in observations], indent=2),
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "scenario": config.scenario_id,
                "run_id": backend.run_id,
                "exported": [str(plan_csv), str(plan_json), str(template_csv)],
                "measurements": [str(measurement_csv), str(measurement_json)],
                "ledger": str(ledger_json),
                "observations": len(observations),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
